# Generated by Django 3.2.15 on 2022-10-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img/banners/', verbose_name='Картинка')),
                ('background', models.BooleanField(verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Фоновый баннер',
                'verbose_name_plural': 'Фоновые баннеры',
            },
        ),
        migrations.CreateModel(
            name='BannerNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotate_speed', models.IntegerField(default=0, verbose_name='Время ротации')),
                ('state', models.BooleanField(verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Новостной баннер',
            },
        ),
        migrations.CreateModel(
            name='BannerUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotate_speed', models.IntegerField(default=0, verbose_name='Время ротации')),
                ('state', models.BooleanField(verbose_name='Состояние')),
            ],
            options={
                'verbose_name': 'Верхний баннер',
            },
        ),
        migrations.CreateModel(
            name='BannerNewsPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='dist/img/banners/', verbose_name='Изображение')),
                ('banner_news', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banners.bannernews')),
            ],
        ),
        migrations.CreateModel(
            name='BannerMainUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='dist/img/banners', verbose_name='Изображение')),
                ('test', models.TextField(verbose_name='Описание баннера')),
                ('banner_up', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banners.bannerup')),
            ],
        ),
    ]
