# Generated by Django 3.2.15 on 2022-10-10 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannermainup',
            old_name='test',
            new_name='text',
        ),
    ]
