# Generated by Django 3.2.15 on 2022-10-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_auto_20221010_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermainup',
            name='url',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='bannernewspromo',
            name='url',
            field=models.URLField(null=True, verbose_name='Ссылка'),
        ),
    ]
