# Generated by Django 3.2.15 on 2022-10-10 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_auto_20221010_2355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermainup',
            name='image',
            field=models.ImageField(upload_to='img/banners', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bannernewspromo',
            name='image',
            field=models.ImageField(upload_to='img/banners/', verbose_name='Изображение'),
        ),
    ]
