# Generated by Django 3.2.15 on 2022-10-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_auto_20221011_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerup',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Состояние'),
        ),
    ]
