# Generated by Django 3.2.15 on 2022-10-10 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_alter_bannerup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerup',
            name='state',
            field=models.BooleanField(verbose_name='Состояние'),
        ),
    ]
