# Generated by Django 3.2.15 on 2022-10-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_alter_bannerup_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbackground',
            name='image',
            field=models.ImageField(null=True, upload_to='img/banners/', verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='bannermainup',
            name='image',
            field=models.ImageField(null=True, upload_to='img/banners', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bannernewspromo',
            name='image',
            field=models.ImageField(null=True, upload_to='img/banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='bannerup',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
