# Generated by Django 3.2.15 on 2022-10-10 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0009_auto_20221011_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermainup',
            name='banner_up',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='banners.bannerup'),
        ),
        migrations.AlterField(
            model_name='bannernewspromo',
            name='banner_news',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='banners.bannernews'),
        ),
    ]
