# Generated by Django 3.2.15 on 2022-10-10 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_auto_20221011_0048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermainup',
            name='banner_up',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banners.bannerup'),
        ),
    ]
