# Generated by Django 3.2.15 on 2022-10-11 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0014_alter_bannerbackground_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bannerbackground',
            old_name='image',
            new_name='imageBackground',
        ),
    ]
