# Generated by Django 3.2.15 on 2022-10-12 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0015_rename_image_bannerbackground_imagebackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbackground',
            name='imageBackground',
            field=models.ImageField(default='img/background/back.jpg', upload_to='img/background/', verbose_name='Картинка'),
        ),
    ]
