# Generated by Django 3.2.15 on 2022-10-12 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0018_auto_20221012_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernewspromo',
            name='banner_news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.bannernews'),
        ),
    ]
