# Generated by Django 3.2.15 on 2022-10-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0020_alter_bannernewspromo_banner_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernewspromo',
            name='image',
            field=models.ImageField(null=True, upload_to='img/banners/'),
        ),
        migrations.AlterField(
            model_name='bannernewspromo',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
