# Generated by Django 3.2.15 on 2022-10-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0021_auto_20221014_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannernewspromo',
            name='imageB',
            field=models.ImageField(null=True, upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='bannernewspromo',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
