# Generated by Django 3.2.15 on 2022-10-14 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0022_auto_20221014_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannernewspromo',
            name='imageB',
        ),
    ]
