# Generated by Django 3.2.15 on 2022-10-17 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0024_auto_20221016_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernewspromo',
            name='promo',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
