# Generated by Django 3.2.15 on 2022-10-18 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0025_alter_bannernewspromo_promo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernewspromo',
            name='banner_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='banners.bannernews'),
        ),
        migrations.AlterField(
            model_name='bannernewspromo',
            name='promo',
            field=models.BooleanField(default=False),
        ),
    ]
