# Generated by Django 3.2.15 on 2022-10-18 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0026_auto_20221018_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernews',
            name='state',
            field=models.BooleanField(blank=True, default=False, verbose_name='Состояние'),
        ),
    ]
