# Generated by Django 3.2.15 on 2022-10-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0027_alter_bannernews_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernews',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Состояние'),
        ),
    ]
