# Generated by Django 3.2.15 on 2022-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0028_alter_bannernews_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernews',
            name='rotate_speed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
