# Generated by Django 3.2.15 on 2022-10-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0029_alter_bannernews_rotate_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernews',
            name='rotate_speed',
            field=models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')], default=5),
        ),
    ]
