# Generated by Django 3.2.15 on 2022-10-20 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0030_alter_bannernews_rotate_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernewspromo',
            name='banner_news',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banners.bannernews'),
        ),
    ]
