# Generated by Django 3.2.15 on 2022-10-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0031_alter_bannernewspromo_banner_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerbackground',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
