# Generated by Django 3.2.15 on 2022-10-23 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0033_alter_bannerbackground_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbackground',
            name='color',
            field=models.CharField(default='', max_length=7),
        ),
    ]
