# Generated by Django 3.2.15 on 2022-10-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0034_alter_bannerbackground_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerup',
            name='rotate_speed',
            field=models.IntegerField(choices=[(5, '5с'), (10, '10с'), (15, '15с')], default=5),
        ),
        migrations.AlterField(
            model_name='bannerup',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Состояние'),
        ),
    ]
