# Generated by Django 3.2.15 on 2022-11-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0037_alter_bannerbackground_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerbackground',
            name='background',
            field=models.BooleanField(default='', verbose_name='Состояние'),
        ),
    ]
