# Generated by Django 3.2.15 on 2023-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0038_alter_bannerbackground_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannermainup',
            name='image',
            field=models.ImageField(null=True, upload_to='img/banners/', verbose_name='Изображение'),
        ),
    ]
