# Generated by Django 3.2.15 on 2023-01-15 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0039_alter_bannermainup_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernews',
            name='rotate_speed',
            field=models.IntegerField(choices=[(500, '5с'), (1000, '10с'), (1500, '15с')], default=5),
        ),
        migrations.AlterField(
            model_name='bannerup',
            name='rotate_speed',
            field=models.IntegerField(choices=[(500, '5с'), (1000, '10с'), (1500, '15с')], default=5),
        ),
    ]
