# Generated by Django 3.2.15 on 2023-01-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0040_auto_20230115_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannernews',
            name='rotate_speed',
            field=models.IntegerField(choices=[(5000, '5с'), (10000, '10с'), (15000, '15с')], default=5),
        ),
        migrations.AlterField(
            model_name='bannerup',
            name='rotate_speed',
            field=models.IntegerField(choices=[(5000, '5с'), (10000, '10с'), (15000, '15с')], default=5),
        ),
    ]
