# Generated by Django 3.2.15 on 2022-10-10 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Номер1', max_length=32, verbose_name='Сессия')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Дата сеанса')),
                ('film', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.film')),
                ('hall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.hall')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Имя')),
                ('surname', models.CharField(max_length=32, verbose_name='Фамилия')),
                ('nickname', models.CharField(max_length=32, verbose_name='Ник')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=32, verbose_name='Ник')),
                ('card_number', models.IntegerField(verbose_name='Номер карты')),
                ('language', models.BooleanField(verbose_name='Состояние')),
                ('gender', models.BooleanField(verbose_name='Состояние')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='+999999999', regex='^\\+?1?\\d{9,15}$')])),
                ('birthday_date', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Когда зарегистрировался')),
                ('confirm_password', models.CharField(max_length=32, verbose_name='Пароль')),
                ('city', models.CharField(max_length=32, verbose_name='Город')),
            ],
        ),
        migrations.CreateModel(
            name='Tiket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField(default=0, verbose_name='Ряд')),
                ('price', models.PositiveSmallIntegerField(default=0, verbose_name='Цена')),
                ('place', models.PositiveSmallIntegerField(default=0, verbose_name='Место')),
                ('booking', models.BooleanField(verbose_name='Состояние')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.session')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
    ]
