# Generated by Django 3.2.15 on 2022-10-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiket',
            name='booking',
            field=models.BooleanField(verbose_name='Бронь'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.BooleanField(verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.BooleanField(verbose_name='Язык'),
        ),
    ]
