# Generated by Django 3.2.15 on 2022-11-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221111_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('m', 'Муж.'), ('f', 'Жен.')], max_length=10),
        ),
    ]
