# Generated by Django 3.2.15 on 2022-11-12 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HtmlTemplate', models.FileField(upload_to='file/mail/', verbose_name='Рассылка')),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
