# Generated by Django 3.2.15 on 2022-11-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='HtmlTemplate',
            field=models.FileField(blank=True, upload_to='file/mail/', verbose_name='Рассылка'),
        ),
    ]
