# Generated by Django 3.2.15 on 2022-11-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_mail_htmltemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='HtmlTemplate',
            field=models.FileField(blank=True, upload_to='templates/file/mail/', verbose_name='Рассылка'),
        ),
    ]
