# Generated by Django 3.2.15 on 2022-11-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_mail_htmltemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='HtmlTemplate',
            field=models.FileField(blank=True, upload_to='users/templates/file/mail', verbose_name='Рассылка'),
        ),
    ]
