# Generated by Django 3.2.15 on 2022-11-24 15:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_mail_htmltemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='+999999999', regex='^\\+?1?\\d{9,11}$')]),
        ),
    ]
