# Generated by Django 3.2.15 on 2022-11-25 19:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(message='Формат телефона +80555555555 до 12 символов', regex='^\\+?1?\\d{9,12}$')]),
        ),
    ]
