# Generated by Django 3.2.15 on 2022-12-03 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата сеанса'),
        ),
    ]
