# Generated by Django 3.2.15 on 2022-12-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20221203_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='dateTime',
            field=models.TimeField(null=True, verbose_name='Дата сеанса'),
        ),
    ]
