# Generated by Django 3.2.15 on 2022-12-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_session_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='t2d',
            field=models.BooleanField(default=True, verbose_name='2d'),
        ),
    ]
