version: "4.15"
services:
  nginx:
    build: ./nginx
    restart: on-failure
    volumes:
      - static_volume:/kinoCMS/static
      - media_volume:/kinoCMS/media
    ports:
      - "80:80"
    depends_on:
      - web
  web:
    build: .
    restart: always
    command: sh -c "
                    
                    python server.py"
    volumes:
      - static_volume:/kinoCMS/static
      - media_volume:/kinoCMS/media
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:14.6
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  static_volume:
  media_volume:
  postgres_data: