# Generated by Django 3.2.15 on 2022-10-10 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallerySeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Кинотеатр')),
                ('description', models.TextField(verbose_name='Описание')),
                ('condition', models.TextField(verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='img/cinema/', verbose_name='Лого')),
                ('banner_up_image', models.ImageField(upload_to='img/cinema/', verbose_name='Баннер')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер зала')),
                ('description', models.TextField(verbose_name='Описание')),
                ('scheme', models.ImageField(upload_to='img/hall/', verbose_name='План зала')),
                ('banner_up_image', models.ImageField(upload_to='img/hall/', verbose_name='Баннер')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='Дата создания')),
                ('cinema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cinema.cinema')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Фильм')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='img/films/', verbose_name='Главное изображение')),
                ('trailer_url', models.URLField(unique=True)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Примьера в мире')),
                ('state', models.BooleanField(verbose_name='Состояние')),
                ('type2d', models.BooleanField(verbose_name='Состояние')),
                ('type3d', models.BooleanField(verbose_name='Состояние')),
                ('typeIMAX', models.BooleanField(verbose_name='Состояние')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo')),
            ],
        ),
    ]
