# Generated by Django 3.2.15 on 2022-10-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallerySeo', '0001_initial'),
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallerySeo.gallery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallerySeo.seo'),
        ),
        migrations.AlterField(
            model_name='film',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallerySeo.gallery'),
        ),
        migrations.AlterField(
            model_name='film',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallerySeo.seo'),
        ),
        migrations.AlterField(
            model_name='film',
            name='type2d',
            field=models.BooleanField(verbose_name='2d'),
        ),
        migrations.AlterField(
            model_name='film',
            name='type3d',
            field=models.BooleanField(verbose_name='3d'),
        ),
        migrations.AlterField(
            model_name='film',
            name='typeIMAX',
            field=models.BooleanField(verbose_name='IMAX'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallerySeo.gallery'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gallerySeo.seo'),
        ),
    ]
