# Generated by Django 3.2.15 on 2022-10-26 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20221010_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='state',
        ),
    ]
