# Generated by Django 3.2.15 on 2022-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_remove_film_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.CharField(max_length=2, verbose_name='Номер зала'),
        ),
    ]
