# Generated by Django 3.2.15 on 2022-10-31 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallerySeo', '0003_auto_20221027_1433'),
        ('cinema', '0004_alter_hall_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo'),
        ),
        migrations.AlterField(
            model_name='film',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery'),
        ),
        migrations.AlterField(
            model_name='film',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='gallery',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='seo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo'),
        ),
    ]
