# Generated by Django 3.2.15 on 2022-11-02 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0007_alter_hall_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.CharField(max_length=2, unique=True, verbose_name='Номер зала'),
        ),
        migrations.AlterUniqueTogether(
            name='hall',
            unique_together={('number', 'cinema')},
        ),
    ]
