# Generated by Django 3.2.15 on 2022-11-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0008_auto_20221102_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.CharField(max_length=2, verbose_name='Номер зала'),
        ),
    ]
