# Generated by Django 3.2.15 on 2022-11-29 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0009_alter_hall_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.CharField(max_length=1, verbose_name='Номер зала'),
        ),
    ]
