# Generated by Django 3.2.15 on 2022-12-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0011_alter_hall_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='film',
            name='title_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='film',
            name='title_uk',
            field=models.CharField(max_length=32, null=True, verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='number',
            field=models.CharField(max_length=3, verbose_name="{% trans 'Номер зала' %}"),
        ),
    ]
