# Generated by Django 3.2.15 on 2022-12-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0012_auto_20221227_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='condition_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='condition_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Кинотеатр'),
        ),
        migrations.AddField(
            model_name='cinema',
            name='name_uk',
            field=models.CharField(max_length=32, null=True, verbose_name='Кинотеатр'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hall',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='hall',
            name='number_ru',
            field=models.CharField(max_length=3, null=True, verbose_name="{% trans 'Номер зала' %}"),
        ),
        migrations.AddField(
            model_name='hall',
            name='number_uk',
            field=models.CharField(max_length=3, null=True, verbose_name="{% trans 'Номер зала' %}"),
        ),
    ]
