# Generated by Django 3.2.15 on 2022-12-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0014_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='release_date',
            field=models.DateField(verbose_name='Примьера в мире'),
        ),
    ]
