# Generated by Django 3.2.15 on 2022-12-27 22:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0015_alter_film_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='create_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
