# Generated by Django 3.2.15 on 2023-01-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0016_alter_hall_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(),
        ),
    ]
