# Generated by Django 3.2.15 on 2023-01-20 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0018_auto_20230116_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.TextField(),
        ),
    ]
