# Generated by Django 3.2.15 on 2023-01-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0019_alter_film_trailer_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='trailer_url',
            field=models.URLField(),
        ),
    ]
