# Generated by Django 3.2.15 on 2022-10-10 10:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gallerySeo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HtmlTemplate', models.FileField(upload_to='file/mail/', verbose_name='Рассылка')),
            ],
        ),
        migrations.CreateModel(
            name='TemplatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(verbose_name='Состояние')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('main_image', models.ImageField(upload_to='img/templatePage/', verbose_name='Главное изображение')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='NewsPromotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(verbose_name='Состояние')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('date_publication', models.DateField(blank=True, null=True, verbose_name='Примьера в мире')),
                ('main_image', models.ImageField(upload_to='img/newsPromotions/', verbose_name='Главное изображение')),
                ('video_url', models.URLField(unique=True)),
                ('is_promotions', models.BooleanField(verbose_name='Состояние')),
                ('gallery', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.gallery')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(verbose_name='Состояние')),
                ('phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='+999999999', regex='^\\+?1?\\d{9,15}$')])),
                ('aditional_phone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='+999999999', regex='^\\+?1?\\d{9,15}$')])),
                ('seo_text', models.TextField(verbose_name='Описание')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo')),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(verbose_name='Состояние')),
                ('cinema_name', models.CharField(max_length=32, verbose_name='Название')),
                ('address', models.TextField(verbose_name='Описание')),
                ('coordinate', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True, verbose_name='Координаты')),
                ('logo', models.ImageField(upload_to='img/contacts/', verbose_name='Изображение')),
                ('seo', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='gallerySeo.seo')),
            ],
        ),
    ]
