# Generated by Django 3.2.15 on 2022-11-05 18:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_newspromotions_is_promotions'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepage',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 5, 18, 49, 40, 664430, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
