# Generated by Django 3.2.15 on 2022-11-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_templatepage_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatepage',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Поле'),
        ),
    ]
