# Generated by Django 3.2.15 on 2022-11-07 15:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_templatepage_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainpage',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
