# Generated by Django 3.2.15 on 2022-11-08 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_mainpage_date_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='date_publication',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
