# Generated by Django 3.2.15 on 2022-11-08 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_contacts_date_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='coordinate',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Координаты'),
            preserve_default=False,
        ),
    ]
