# Generated by Django 3.2.15 on 2022-11-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_contacts_coordinate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='cinema_name',
            field=models.CharField(max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='coordinate',
            field=models.TextField(null=True, verbose_name='Координаты'),
        ),
    ]
