# Generated by Django 3.2.15 on 2022-11-12 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20221110_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mail',
        ),
    ]
