# Generated by Django 3.2.15 on 2022-11-25 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_delete_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='aditional_phone',
            field=models.CharField(blank=True, max_length=17),
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='phone',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
