# Generated by Django 3.2.15 on 2022-12-27 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_auto_20221125_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='address_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='address_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='cinema_name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='cinema_name_uk',
            field=models.CharField(max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='seo_text_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='mainpage',
            name='seo_text_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='name_ru',
            field=models.CharField(max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='newspromotions',
            name='name_uk',
            field=models.CharField(max_length=32, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='templatepage',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='templatepage',
            name='description_uk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='templatepage',
            name='name_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='templatepage',
            name='name_uk',
            field=models.CharField(max_length=150, null=True, verbose_name='Название'),
        ),
    ]
