# Generated by Django 3.2.15 on 2022-10-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerySeo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Gallery'},
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='name',
        ),
    ]
