# Generated by Django 3.2.15 on 2022-10-27 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallerySeo', '0002_auto_20221026_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seo',
            old_name='description',
            new_name='seo_description',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='keywords',
            new_name='seo_keywords',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='title',
            new_name='seo_title',
        ),
        migrations.RenameField(
            model_name='seo',
            old_name='url',
            new_name='seo_url',
        ),
    ]
