# Generated by Django 3.2.15 on 2023-01-17 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerySeo', '0003_auto_20221027_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='seo_title',
            field=models.CharField(max_length=150, validators=[django.core.validators.MaxLengthValidator(150)], verbose_name='Название'),
        ),
    ]
