# Generated by Django 3.2.15 on 2023-01-17 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallerySeo', '0005_alter_seo_seo_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seo',
            name='seo_keywords',
            field=models.CharField(max_length=150, verbose_name='Слова'),
        ),
        migrations.AlterField(
            model_name='seo',
            name='seo_title',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
